---
development:
  cloud_name: dfvucpnfl
  api_key: 295135318988452
  api_secret: IvCf10cKUtkabhtDMCFe-Zs4LzM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dfvucpnfl
  api_key: 295135318988452
  api_secret: IvCf10cKUtkabhtDMCFe-Zs4LzM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dfvucpnfl
  api_key: 295135318988452
  api_secret: IvCf10cKUtkabhtDMCFe-Zs4LzM
  enhance_image_tag: true
  static_image_support: false
